# Generated by Django 4.2.4 on 2023-08-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_image')),
                ('title', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=32)),
                ('memory', models.IntegerField()),
                ('memory_type', models.CharField(choices=[('GDDR4', 'GDDR4'), ('GDDR5', 'GDDR5'), ('GDDR6', 'GDDR6')], max_length=16)),
                ('price', models.IntegerField()),
                ('rate', models.FloatField(default=0)),
                ('discount', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
